server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://127.0.0.1:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: entradas-service
          uri: http://entradas-service:8081
          predicates:
            - Path=/api/entradas/**
        - id: salidas-service
          uri: http://salidas-service:8082
          predicates:
            - Path=/api/salidas/**
        - id: resumen-service
          uri: http://resumen-service:8083
          predicates:
            - Path=/api/resumen/**
