server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: entradas-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/entradas/**
        - id: salidas-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/salidas/**
        - id: resumen-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/resumen/**
